//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceLayer.ResourceFile", typeof(ResourceFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some problem while processing your request. Please try again later..
        /// </summary>
        public static string Failure_General {
            get {
                return ResourceManager.GetString("Failure_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid request. Please try again..
        /// </summary>
        public static string Invalid_Request {
            get {
                return ResourceManager.GetString("Invalid_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login session has been expired. Please try again..
        /// </summary>
        public static string Login_Session_Expired {
            get {
                return ResourceManager.GetString("Login_Session_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail sending failed..
        /// </summary>
        public static string Mail_Failure {
            get {
                return ResourceManager.GetString("Mail_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail sent successfully..
        /// </summary>
        public static string Mail_Success {
            get {
                return ResourceManager.GetString("Mail_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your page session has been expired. Please try again..
        /// </summary>
        public static string Page_Session_Expired {
            get {
                return ResourceManager.GetString("Page_Session_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found..
        /// </summary>
        public static string Record_Not_Found {
            get {
                return ResourceManager.GetString("Record_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comment added successfully..
        /// </summary>
        public static string Review_Insert_Success {
            get {
                return ResourceManager.GetString("Review_Insert_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Operation you have performed is completed successfully..
        /// </summary>
        public static string Success_General {
            get {
                return ResourceManager.GetString("Success_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This registration has been de-activated by Regulator. .
        /// </summary>
        public static string User_Account_Inactive {
            get {
                return ResourceManager.GetString("User_Account_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email ID is already verified. Please login to proceed further..
        /// </summary>
        public static string User_Already_Verified {
            get {
                return ResourceManager.GetString("User_Already_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email ID is already registered..
        /// </summary>
        public static string User_Email_Already_Registered {
            get {
                return ResourceManager.GetString("User_Email_Already_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID not found..
        /// </summary>
        public static string User_Email_Not_Found {
            get {
                return ResourceManager.GetString("User_Email_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully..
        /// </summary>
        public static string User_Insert_Success {
            get {
                return ResourceManager.GetString("User_Insert_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        public static string User_Invalid_Password {
            get {
                return ResourceManager.GetString("User_Invalid_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email ID or Password..
        /// </summary>
        public static string User_Invalid_Username_Password {
            get {
                return ResourceManager.GetString("User_Invalid_Username_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully..
        /// </summary>
        public static string User_Password_Change_Success {
            get {
                return ResourceManager.GetString("User_Password_Change_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password created successfully..
        /// </summary>
        public static string User_Password_Create_Success {
            get {
                return ResourceManager.GetString("User_Password_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User verification is pending. Please check your mail and click on verification link to proceed further..
        /// </summary>
        public static string User_Verification_Pending {
            get {
                return ResourceManager.GetString("User_Verification_Pending", resourceCulture);
            }
        }
    }
}
